name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install --omit=dev

    - name: Deploy to Railway
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        REPO_NAME: ${{ secrets.REPO_NAME }}
        ADMIN_CHAT_ID: ${{ secrets.ADMIN_CHAT_ID }}
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        railway login --token ${{ secrets.RAILWAY_TOKEN }}
        railway up